/* Automatically generated by
 * tools::package_native_routine_registration_skeleton in r-devel from
 * 2017-03-27 */
/* Future versions of Rcpp may generate this, so this may not be
 * needed in the future */

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP _flexsurv_basis_matrix(SEXP, SEXP);
extern SEXP _flexsurv_basis_vector(SEXP, SEXP);
extern SEXP _flexsurv_check_genf(SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_check_gengamma(SEXP, SEXP, SEXP);
extern SEXP _flexsurv_check_gompertz(SEXP, SEXP);
extern SEXP _flexsurv_check_llogis(SEXP, SEXP);
extern SEXP _flexsurv_dbasis_matrix(SEXP, SEXP);
extern SEXP _flexsurv_dbasis_vector(SEXP, SEXP);
extern SEXP _flexsurv_dexph(SEXP);
extern SEXP _flexsurv_dgenf_work(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_dgengamma_work(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_dgompertz_work(SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_dllogis_work(SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_exph(SEXP);
extern SEXP _flexsurv_pgenf_work(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_pgengamma_work(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_pgompertz_work(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _flexsurv_pllogis_work(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_flexsurv_basis_matrix",   (DL_FUNC) &_flexsurv_basis_matrix,   2},
    {"_flexsurv_basis_vector",   (DL_FUNC) &_flexsurv_basis_vector,   2},
    {"_flexsurv_check_genf",     (DL_FUNC) &_flexsurv_check_genf,     4},
    {"_flexsurv_check_gengamma", (DL_FUNC) &_flexsurv_check_gengamma, 3},
    {"_flexsurv_check_gompertz", (DL_FUNC) &_flexsurv_check_gompertz, 2},
    {"_flexsurv_check_llogis",   (DL_FUNC) &_flexsurv_check_llogis,   2},
    {"_flexsurv_dbasis_matrix",  (DL_FUNC) &_flexsurv_dbasis_matrix,  2},
    {"_flexsurv_dbasis_vector",  (DL_FUNC) &_flexsurv_dbasis_vector,  2},
    {"_flexsurv_dexph",          (DL_FUNC) &_flexsurv_dexph,          1},
    {"_flexsurv_dgenf_work",     (DL_FUNC) &_flexsurv_dgenf_work,     6},
    {"_flexsurv_dgengamma_work", (DL_FUNC) &_flexsurv_dgengamma_work, 5},
    {"_flexsurv_dgompertz_work", (DL_FUNC) &_flexsurv_dgompertz_work, 4},
    {"_flexsurv_dllogis_work",   (DL_FUNC) &_flexsurv_dllogis_work,   4},
    {"_flexsurv_exph",           (DL_FUNC) &_flexsurv_exph,           1},
    {"_flexsurv_pgenf_work",     (DL_FUNC) &_flexsurv_pgenf_work,     7},
    {"_flexsurv_pgengamma_work", (DL_FUNC) &_flexsurv_pgengamma_work, 6},
    {"_flexsurv_pgompertz_work", (DL_FUNC) &_flexsurv_pgompertz_work, 5},
    {"_flexsurv_pllogis_work",   (DL_FUNC) &_flexsurv_pllogis_work,   5},
    {NULL, NULL, 0}
};

void R_init_flexsurv(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, TRUE);
}
