# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgengamma_work <- function(x, mu, sigma, Q, log) {
    .Call('flexsurv_dgengamma_work', PACKAGE = 'flexsurv', x, mu, sigma, Q, log)
}

pgengamma_work <- function(q, mu, sigma, Q, lower_tail, give_log) {
    .Call('flexsurv_pgengamma_work', PACKAGE = 'flexsurv', q, mu, sigma, Q, lower_tail, give_log)
}

check.gengamma <- function(mu, sigma, Q) {
    .Call('flexsurv_check_gengamma', PACKAGE = 'flexsurv', mu, sigma, Q)
}

dgompertz_work <- function(x, shape, rate, log) {
    .Call('flexsurv_dgompertz_work', PACKAGE = 'flexsurv', x, shape, rate, log)
}

exph <- function(y) {
    .Call('flexsurv_exph', PACKAGE = 'flexsurv', y)
}

dexph <- function(y) {
    .Call('flexsurv_dexph', PACKAGE = 'flexsurv', y)
}

